 name: "protocol buffer go stubs generation"
 on:
   push:
     branches:
       - master
       - main
 jobs:
   protoc:
     name: "Generate"
     runs-on: "ubuntu-latest"
     permissions: write-all
     strategy:
       matrix:
        service: ["order"]
     steps:
       - name: Install Go
         uses: actions/setup-go@v2
         with:
           go-version: 1.21
       - uses: actions/checkout@v4
       - name: Only generate the tag
         id: tag_version
         uses: mathieudutour/github-tag-action@v6.1
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           default_bump: patch
           tag_prefix: golang/order/v
           dry_run: true
       - name: Generate for Golang
         shell: bash
         env:
           SERVICE_NAME: ${{ matrix.service }}
           TAG: ${{ steps.tag_version.outputs.new_tag }}
         run: |
           chmod +x "${GITHUB_WORKSPACE}/run.sh"
           ./run.sh ${{ matrix.service }}
       - name: Create a GitHub release
         uses: ncipollo/release-action@v1
         with:
           tag: ${{ steps.tag_version.outputs.new_tag }}
           name: Release ${{ steps.tag_version.outputs.new_tag }}
           body: ${{ steps.tag_version.outputs.changelog }}

