 name: "protocol buffer go stubs generation"
 on:
   push:
     tags:
       - '*'
   release:
     types: [published]
   workflow_run:
     workflows: [ "Auto Tag" ]
     types: [ completed ]
 jobs:
   protoc:
     name: "Generate"
     runs-on: "ubuntu-latest"
     permissions: write-all
     strategy:
       matrix:
        service: ["order"]
     steps:
       - name: Install Go
         uses: actions/setup-go@v2
         with:
           go-version: 1.21
       - uses: actions/checkout@v2
       - name: Extract Release Version
         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
       - name: Generate for Golang
         shell: bash
         env:
           SERVICE_NAME: ${{ matrix.service }}
         run: |
           chmod +x "${GITHUB_WORKSPACE}/run.sh"
           ./run.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }}
        
          
