 name: "protocol buffer go stubs generation"
 on:
   push:
     tags:
       - golang**
 jobs:
   protoc:
     name: "Generate"
     runs-on: "ubuntu-latest"
     strategy:
       matrix:
        service: ["order"]
     steps:
       - name: Install Go
         uses: actions/setup-go@v2
         with:
           go-version: 1.21
       - uses: actions/checkout@v2
       - name: Extract Release Version
         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
       - name: Generate for Golang
         shell: bash
         run: |
           chmod +x "${GITHUB_WORKSPACE}/run.sh"
           ./run.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }}
          
